version: '3'

services:
  main:
    build: packages/main
    networks:
      - external
    ports:
      - 3000:80

  topmenu:
    build: packages/topmenu
    networks:
      - external
    ports:
      - 3001:80

  bundleserve:
    build: packages/bundleserve
    networks:
      - external
    ports:
      - 3002:80

networks:
  external:
  internal: